#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSV Reader for NineBus.csv and similar simulation output CSV files.

This module provides a class to read and plot CSV output data generated by
simulation tools (e.g., PSCAD, Simulink) with a similar interface to PSCADReader.
Designed to work with structured CSV files containing grouped signal data.

Usage:
    from readers.csv_reader import CSVReader, plot_vars
    
    # List all signals
    CSVReader.list_signals('samples/NineBus.csv')
    
    # Get signal data
    t, y = CSVReader.get_signal_data(
        'samples/NineBus.csv',
        group='G1',
        signal='Terminal voltage'
    )
    
    # Plot
    plot_vars('Terminal Voltage (p.u.)', t, y, lbl='G1')
"""

import csv
import os
from pathlib import Path
import numpy as np
from math import ceil


class CSVReader:
    """
    A utility class to read and plot CSV output data with caching and downsampling.
    Designed for structured CSV files with grouped signal data (e.g., NineBus.csv).
    
    Expected CSV format:
        Row 1: Group names (e.g., "Standard Model", "G1", "G1", ...)
        Row 2: Signal descriptions (e.g., "Time in s", "Voltage in p.u.", ...)
        Row 3+: Data values (comma-separated)
    """
    
    _cache = {}  # Cache: { (file_path, col_index): (full_t, full_y) }
    
    @classmethod
    def clear_cache(cls):
        """Clear all cached data."""
        cls._cache = {}
    
    @classmethod
    def get_signal_data(cls, fn_csv, group=None, signal=None, col_index=None, max_points=2000):
        """
        Reads signal data from a CSV file with caching and automatic downsampling.
        
        Args:
            fn_csv (str): Path to the CSV file.
            group (str): Generator group name (e.g., 'G1', 'G2', 'G3').
                Optional. If provided, signal must also be provided.
            signal (str): Signal description to extract (e.g., 'Terminal voltage').
                Optional. If provided with group, finds column by matching.
            col_index (int): Direct column index (0-based). Alternative to group/signal.
            max_points (int): Maximum points to return for plotting.
            
        Returns:
            tuple: (t_array, y_array) - potentially downsampled
        """
        # Use either (group + signal) or direct col_index
        if col_index is None:
            assert group is not None and signal is not None, \
                "Either provide group+signal or col_index"
            col_index = cls.get_col_index(fn_csv, group, signal)
            if col_index is None:
                return np.array([]), np.array([])
        
        cache_key = (str(fn_csv), col_index)
        
        # 1. Try to get full data from cache
        if cache_key in cls._cache:
            full_t, full_y = cls._cache[cache_key]
        else:
            # 2. Read from disk if not cached
            full_t, full_y = cls._read_from_disk(fn_csv, col_index)
            if full_t.size > 0:
                cls._cache[cache_key] = (full_t, full_y)
        
        if full_t.size == 0:
            return full_t, full_y
        
        # 3. Downsample if needed
        if full_t.size > max_points:
            return cls.downsample(full_t, full_y, max_points)
        
        return full_t, full_y

    @classmethod
    def read_signal(cls, fn_csv, sgn_name, grp_name):
        """
        Read a signal by name and group name. Convenience wrapper around get_signal_data.
        
        Args:
            fn_csv (str): Path to CSV file.
            sgn_name (str): Signal name/description to match.
            grp_name (str): Group name to match.
            
        Returns:
            tuple: (t_array, y_array) - potentially downsampled
        """
        return cls.get_signal_data(fn_csv, group=grp_name, signal=sgn_name)
    
    @staticmethod
    def _read_from_disk(fn_csv, col_index):
        """Read raw data from CSV file at given column index."""
        path = Path(str(fn_csv))
        if not path.exists():
            return np.array([]), np.array([])
        
        col_idx = int(col_index)
        times = []
        values = []
        
        try:
            with open(path, 'r') as f:
                reader = csv.reader(f)
                for i, row in enumerate(reader):
                    if i < 2:  # Skip header rows
                        continue
                    if len(row) > col_idx:
                        try:
                            t = float(row[0])
                            y = float(row[col_idx])
                            times.append(t)
                            values.append(y)
                        except (ValueError, IndexError):
                            continue
        except Exception as e:
            print(f"Error reading {fn_csv}:[{col_index}]: {e}")
            return np.array([]), np.array([])
        
        if not times:
            return np.array([]), np.array([])
        
        return np.array(times), np.array(values)
    
    @staticmethod
    def get_col_index(fn_csv, group, signal):
        """
        Find column index by matching group name and signal description.
        
        Args:
            fn_csv: CSV file path
            group: Group name (e.g., 'G1')
            signal: Signal description substring to match
            
        Returns:
            int: Column index (0-based), or None if not found
        """
        path = Path(str(fn_csv))
        if not path.exists():
            print(f"File not found: {fn_csv}")
            return None
        
        try:
            with open(path, 'r') as f:
                reader = csv.reader(f)
                rows = list(reader)
                
                if len(rows) < 2:
                    print(f"Invalid CSV format: {fn_csv}")
                    return None
                
                groups_row = [g.strip() for g in rows[0]]
                signals_row = [s.strip() for s in rows[1]]
                
                # Search for matching group and signal
                for col_idx in range(len(groups_row)):
                    if groups_row[col_idx] == group:
                        if signal.lower() in signals_row[col_idx].lower():
                            return col_idx
                
        except Exception as e:
            print(f"Error parsing CSV headers: {e}")
        
        return None
    
    @staticmethod
    def list_signals(fn_csv, verbose=True):
        """
        Parse CSV headers and list all available signals grouped by generator.
        
        Args:
            fn_csv: Path to CSV file
            verbose (bool): If True, prints formatted list to console
            
        Returns:
            list: List of dicts with 'col_index', 'group', 'desc', 'index', 'units', 'full_label'
         """
        from pathlib import Path
        path = Path(str(fn_csv))
        if not path.exists():
            print(f"File not found: {fn_csv}")
            return []
        
        try:
            with open(path, 'r') as f:
                reader = csv.reader(f)
                rows = list(reader)
                
                if len(rows) < 2:
                    print(f"Invalid CSV format: {fn_csv}")
                    return []
                
                groups = [g.strip() for g in rows[0]]
                signals = [s.strip() for s in rows[1]]
                
                result = []
                for col_idx in range(len(groups)):
                    result.append({
                         'col_index': col_idx,
                         'group': groups[col_idx],
                         'desc': signals[col_idx],
                         'index': col_idx,
                         'units': '',
                         'full_label': f"{groups[col_idx]}: {signals[col_idx]}"
                    })
                
                if verbose and result:
                    cls = CSVReader
                    print(f"\n--- Available Signals in {path.name} ---")
                    print("=" * 80)
                    print(f"{'Col':<5} | {'Group':<8} | {'Signal Description'}")
                    print("-" * 80)
                    
                    current_group = None
                    for sig in result:
                        if sig['group'] != current_group:
                            print()   # Blank line between groups
                            current_group = sig['group']
                        
                        print(f"{sig['col_index']:<5} | {sig['group']:<8} | {sig['desc']}")
                    
                    print("=" * 80)
                    print(f"\nTotal: {len(result)} columns (including 'Time' at col 0)")
                
                return result
                
        except Exception as e:
            print(f"Error parsing CSV: {e}")
            return []
    
    @staticmethod
    def downsample(t, y, max_points):
        """
        Downsamples data using a min-max approach to preserve spikes/visual fidelity.
        Divides data into buckets and picks min/max from each.
        
        Args:
            t: Time array
            y: Values array
            max_points: Target maximum points
            
        Returns:
            tuple: (downsampled_t, downsampled_y)
        """
        n = len(t)
        
        # Aim for ~max_points by taking pairs of min/max
        bucket_size = max(1, n // (max_points // 2))
        
        # Reshape to handle buckets
        n_buckets = n // bucket_size
        t_trunc = t[:n_buckets * bucket_size].reshape(n_buckets, bucket_size)
        y_trunc = y[:n_buckets * bucket_size].reshape(n_buckets, bucket_size)
        
        # Get indices of min and max in each bucket
        min_idx = np.argmin(y_trunc, axis=1)
        max_idx = np.argmax(y_trunc, axis=1)
        
        # Create global indices
        offset = np.arange(0, n_buckets * bucket_size, bucket_size)
        idx_a = offset + min_idx
        idx_b = offset + max_idx
        
        # Combine and sort to preserve chronological order
        combined_idx = np.unique(np.concatenate([idx_a, idx_b]))
        
        return t[combined_idx], y[combined_idx]
    
    @staticmethod
    def get_data_summary(fn_csv):
        """
        Get a summary of the CSV file (groups, columns, data range).
        
        Args:
            fn_csv: Path to CSV file
            
        Returns:
            dict: Summary information
        """
        from pathlib import Path
        path = Path(str(fn_csv))
        if not path.exists():
            return {"error": f"File not found: {fn_csv}"}
        
        try:
            with open(path, 'r') as f:
                reader = csv.reader(f)
                rows = list(reader)
            
            groups = [g.strip() for g in rows[0]]
            signals = [s.strip() for s in rows[1]]
            
            # Get data stats
            time_col = float(rows[2][0])
            data_start = float(rows[2][0])  # First data row
            data_end = float(rows[-1][0])  # Last data row
            
            summary = {
                'total_rows': len(rows),
                'total_columns': len(groups),
                'groups': list(set(groups)),
                'time_range': (data_start, data_end),
                'samples': len(rows) - 2,  # Subtract header rows
            }
            
            print(f"\n--- CSV Summary: {path.name} ---")
            print(f"Total rows: {summary['total_rows']}")
            print(f"Total columns: {summary['total_columns']}")
            print(f"Groups: {', '.join(summary['groups'])}")
            print(f"Time range: {data_start:.4f}s → {data_end:.4f}s")
            print(f"Number of samples: {summary['samples']}")
            print(f"Sampling interval: {(data_end - data_start) / summary['samples']:.6f}s")
            
            return summary
            
        except Exception as e:
            return {"error": str(e)}


# ============================================================================
# Plotting Utilities (similar to pscad_reader.py)
# ============================================================================

def plot_vars(sgname, t, y, lbl, fname=None, xmin=None, xmax=None, 
              ymin=None, ymax=None, legend=True, color='blue'):
    """
    Plot signal data with consistent formatting.
    
    Args:
        sgname: Signal name (ylabel)
        t: Time array
        y: Values array
        lbl: Label text (or list of labels)
        fname: Optional output filename (saves as PDF)
        xmin, xmax: X-axis limits
        ymin, ymax: Y-axis limits
        legend: Show legend
        color: Default line color
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available for plotting")
        return None, None
    
    # Apply format (from pscad_reader.py)
    def format_axes(ax):
        for spine in ['top', 'right']:
            ax.spines[spine].set_visible(False)
        for spine in ['left', 'bottom']:
            ax.spines[spine].set_linewidth(0.5)
        ax.xaxis.set_ticks_position('bottom')
        ax.yaxis.set_ticks_position('left')
        ax.grid(linestyle=':')
        for axis in [ax.xaxis, ax.yaxis]:
            ax.tick_params(length=0)
        return ax
    
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(t, y, color=color, linewidth=0.8)
    ax.set_ylabel(sgname)
    ax.set_xlabel('Time (s)')
    
    if xmin is not None and xmax is not None:
        ax.set_xlim(xmin, xmax)
    if ymin is not None and ymax is not None:
        ax.set_ylim(ymin, ymax)
    
    if legend:
        lbl_text = lbl if isinstance(lbl, str) else lbl[0]
        ax.legend(loc='best', fontsize=8)
    ax.grid(True, alpha=0.3)
    
    try:
        plt.tight_layout()
    except:
        pass
    
    # Save if filename provided
    if fname:
        fig.savefig(f"{fname}.png", dpi=150, bbox_inches='tight')
        print(f"Saved: {fname}.png")
    
    return fig, ax


# ============================================================================
# Main usage example
# ============================================================================

if __name__ == "__main__":
    """
    Example usage for NineBus.csv:
    
    # List all signals
    CSVReader.list_signals('samples/NineBus.csv')
    
    # Get data for specific signal
    t, y = CSVReader.get_signal_data(
        'samples/NineBus.csv',
        group='G1',
        signal='Terminal voltage'
    )
    
    if t.size > 0:
        plot_vars('Terminal Voltage (p.u.)', t, y, 'G1')
        plt.show()
    """
    
    import matplotlib.pyplot as plt
    
    # Example: List signals from NineBus.csv
    sample_file = 'samples/NineBus.csv'
    
    if Path(sample_file).exists():
        print("Available signals:")
        CSVReader.list_signals(sample_file)
        
        # Example: Plot G1 Terminal Voltage
        print("\nPlotting G1 Terminal Voltage...")
        t, y = CSVReader.get_signal_data(
            sample_file, 
            group='G1',
            signal='Terminal voltage'
        )
        
        if t.size > 0:
            fig, ax = plot_vars('Terminal Voltage (p.u.)', t, y, 'G1')
            fig.savefig('G1_terminal_voltage.png', dpi=150, bbox_inches='tight')
            print("Generated: G1_terminal_voltage.png")
            plt.close(fig)